### PR TITLE
Bumping up version of Caddy Server.

### PR DESCRIPTION
**Pull request by mohammedzee1000**
This bumps up Caddy Server version for 0.11.0

### CODE REVIEW

**Comment by mohammedzee1000** [comment]
ping @jperrin @kbsingh

**Comment by jperrin** [comment]
Seems minor enough.

**Comment by mohammedzee1000** [comment]
@jperrin I am maintaining the same on my fork atm, as some plugins are needed by the users of this container.

 https://github.com/mohammedzee1000/caddy/tree/centos_release

**Comment by jperrin** [comment]
I don't see that documented in the that dir anywhere within the CentOS-Dockerfiles. Someone trying to recreate that container won't be able to. We should probably add something around that so it's useful to outside folks as well.

**Pull request merged**
