### PR TITLE
Make it possible to specify charset and collation for MariaDB

### PR DESCRIPTION
**Pull request by atodorov**
For my database I use `CHARACTER SET utf8 COLLATE utf8_unicode_ci` and this PR makes it possible to configure these. 

I'm not sure what to do about versioning. Is the image on Docker Hub going to be rebuilt after this PR has been merged ?

### CODE REVIEW

**Comment by atodorov** [comment]
ping, any updates here ?

**Comment by jperrin** [comment]
yeah, the image in docker hub updates when this repo gets bumped. 

This looks okay to me.

**Comment by atodorov** [comment]
@jperrin thanks for the merge. How do I know that the upstream image has been updated ?

**Comment by jperrin** [comment]
The builds page will tell you. 

https://hub.docker.com/r/centos/mariadb/builds/

**Pull request merged**
