### PR TITLE
Sentry, updated to upstream 8.22

### PR DESCRIPTION
**Pull request by mmclanerh**

### CODE REVIEW

**Comment by kbsingh** [comment]
has someone does a test build and get the required results ?

**Comment by arrfab** [comment]
Hi guys .. does it exist a policy that would permit us to deliver containers with binary blobs not built on CentOS infra ? just as an example : https://github.com/CentOS/CentOS-Dockerfiles/pull/165/files#diff-79952346e1625ae08b8f366e2f89fd1fR43

**Comment by kbsingh** [comment]
@arrfab yeah, thats fine - much like SIG content. The ownership of the artifact is then upto the upstream to maintain. As long as the licensing permits us to do this, it should be ok. 

If possible, I would really like to see the content itself moved ( and therefore built / validated ) as a part of the CentOS Ecosystem though.  Even if its not rpm.

**Comment by mmclanerh** [comment]
log of build output https://github.com/CentOS/container-index/issues/259#issuecomment-360194419

**Comment by mmclanerh** [comment]
confirmed --this seems to be working.  

```
8:48:41 [INFO] sentry.plugins.github: apps-not-configured
*** Starting uWSGI 2.0.15 (64bit) on [Wed Jan 24 18:48:41 2018] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-16) on 24 January 2018 16:30:19
os: Linux-3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Dec 28 14:23:39 EST 2017
nodename: 76af75962e94
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /
detected binary path: /usr/bin/uwsgi
your memory page size is 4096 bytes
detected max file descriptor number: 65536
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 bound to TCP address 0.0.0.0:9000 fd 3
Python version: 2.7.5 (default, Aug  4 2017, 00:39:18)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
Set PythonHome to /usr
Python main interpreter initialized at 0x1e89c70
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
setting request body buffering size to 65536 bytes
mapped 1922048 bytes (1877 KB) for 12 cores
*** Operational MODE: preforking+threaded ***
spawned uWSGI master process (pid: 15)
spawned uWSGI worker 1 (pid: 24, cores: 4)
spawned uWSGI worker 2 (pid: 25, cores: 4)
spawned uWSGI worker 3 (pid: 26, cores: 4)
18:48:42 [INFO] sentry.plugins.github: apps-not-configured
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1e89c70 pid: 24 (default app)
18:48:42 [INFO] sentry.plugins.github: apps-not-configured
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x1e89c70 pid: 26 (default app)
18:48:43 [INFO] sentry.plugins.github: apps-not-configured
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x1e89c70 pid: 25 (default app)
```

image

```
8:48:41 [INFO] sentry.plugins.github: apps-not-configured
*** Starting uWSGI 2.0.15 (64bit) on [Wed Jan 24 18:48:41 2018] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-16) on 24 January 2018 16:30:19
os: Linux-3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Dec 28 14:23:39 EST 2017
nodename: 76af75962e94
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /
detected binary path: /usr/bin/uwsgi
your memory page size is 4096 bytes
detected max file descriptor number: 65536
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 bound to TCP address 0.0.0.0:9000 fd 3
Python version: 2.7.5 (default, Aug  4 2017, 00:39:18)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
Set PythonHome to /usr
Python main interpreter initialized at 0x1e89c70
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
setting request body buffering size to 65536 bytes
mapped 1922048 bytes (1877 KB) for 12 cores
*** Operational MODE: preforking+threaded ***
spawned uWSGI master process (pid: 15)
spawned uWSGI worker 1 (pid: 24, cores: 4)
spawned uWSGI worker 2 (pid: 25, cores: 4)
spawned uWSGI worker 3 (pid: 26, cores: 4)
18:48:42 [INFO] sentry.plugins.github: apps-not-configured
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1e89c70 pid: 24 (default app)
18:48:42 [INFO] sentry.plugins.github: apps-not-configured
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x1e89c70 pid: 26 (default app)
18:48:43 [INFO] sentry.plugins.github: apps-not-configured
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x1e89c70 pid: 25 (default app)
```

**Comment by kbsingh** [comment]
cheers @mmclanerh - happy to have you just own the sentry space on the CentOS-Dockerfiles.

**Pull request merged**
