### PR TITLE
Added dockerfile for atomic registry based off centos.

### PR DESCRIPTION
**Pull request by mohammedzee1000**
@mohammedzee1000 

Based on issue #63 
Dependent on PR #57 

The centos based atomic registry uses centos  and scratch containers in its process instead of a fedora container in the original atomic-registry-quickstart.

### CODE REVIEW

**Comment by jperrin** [comment]
Why is the registry container based on the openshift origin container, rather than a base centos container?

**Comment by mohammedzee1000** [comment]
The openshift origin container is sitting on top of centos 7 already.

**Comment by jperrin** [comment]
Right, I get that. I'm just wondering what the requirement is on an openshift container here? Does the atomic registry rely on openshift to that extent?

**Comment by mohammedzee1000** [comment]
Yes, infact it uses origin docker registry at the back and involves creation of openshift projects where we push the images.

**Pull request closed without merging**
