### PR TITLE
Fixed port number in README file

### PR DESCRIPTION
**Pull request by surajnarwade**

### CODE REVIEW

**Review by mohammedzee1000 — APPROVED** [review]
LGTM this is verified. Thanks @surajnarwade

**Comment by kbsingh** [comment]
i was under the impression that running on port 80 needed priviledged access on the machine running the instance. is that no longer the case ?

**Comment by cdrage** [comment]
@kbsingh It's still the case. This (probably) won't work on orchestrators such as OpenShift

**Comment by surajnarwade** [comment]
@cdrage @kbsingh but container is running on that port only

**Comment by kbsingh** [comment]
so the fix here might be to change the port used inside the container to match the exported port ?

**Pull request closed without merging**
