### PR TITLE
Adding golang base image

### PR DESCRIPTION
**Pull request by mohammedzee1000**

### CODE REVIEW

**Comment by mohammedzee1000** [comment]
@jperrin ping

**Comment by mohammedzee1000** [comment]
@jperrin @kbsingh ping

**Comment by jperrin** [comment]
I don't understand the need for the install.sh script here. Why not just run those commands as part of the Dockerfile itself. It doesn't appear to reduce the layer count based on the need to create the dir, add the script and run.

**Comment by kbsingh** [comment]
@jperrin ping, are we good to merge this in ?

**Comment by kbsingh** [comment]
@mohammedzee1000 can you also post the registry url where the resulting container will land at

**Pull request merged**
