### PR TITLE
Add Dockerfile and README for Tools image

### PR DESCRIPTION
**Pull request by vpavlin**
You can find the built image at https://hub.docker.com/r/vpavlin/centos-tools/

@markllama @jeremyeder PTAL

### CODE REVIEW

**Comment by jeremyeder** [comment]
LGTM :+1:

**Comment by vpavlin** [comment]
@jeremyeder I added also a link to the blog post you published at Project Atomic blog

**Comment by jperrin** [comment]
LGTM

**Comment by jeremyeder** [comment]
Thanks @jperrin will this automatically get built now on the docker hub?

**Comment by jperrin** [comment]
I can add it so that it will. I'll set it up as an automated build.

**Comment by jperrin** [comment]
Build's done. https://hub.docker.com/r/centos/tools/

**Pull request merged**
