### PR TITLE
Added cccp.yml for building rabbitmq container on pipeline.

### PR DESCRIPTION
**Pull request by mohammedzee1000**

### CODE REVIEW

**Comment by mohammedzee1000** [comment]
ping @jperrin

**Comment by jperrin** [comment]
lgtm

**Comment by surajssd** [comment]
@mohammedzee1000 since this is merged does that mean this image will be now be available on `registry.centos.org`? If that is so, I still don't see image there:

```json
$ curl https://registry.centos.org/v2/_catalog | python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2543    0  2543    0     0   2476      0 --:--:--  0:00:01 --:--:--  2478
{
    "repositories": [
        "bamachrn/mattermost-app",
        "bamachrn/mattermost-db",
        "bamachrn/mattermost-web",
        "bamachrn/python",
        "centos/bind",
        "centos/centos",
        "centos/centos-base",
        "centos/django",
        "centos/etherpad",
        "centos/firefox",
        "centos/freeipa",
        "centos/httpd",
        "centos/kubernetes-apiserver",
        "centos/kubernetes-controller-manager",
        "centos/kubernetes-kubelet",
        "centos/kubernetes-master",
        "centos/kubernetes-node",
        "centos/kubernetes-proxy",
        "centos/kubernetes-scheduler",
        "centos/mariadb",
        "centos/memcached",
        "centos/mongo",
        "centos/owncloud",
        "centos/postgres",
        "centos/python",
        "centos/qpid",
        "centos/redis",
        "centos/registry",
        "centos/registry-v2",
        "centos/ssh",
        "centos/systemd",
        "centos/tools",
        "centos/wildfly",
        "centos/wordpress",
        "cockpit/kubernetes",
        "cockpit/ws",
        "container-pipeline/cccp-build",
        "container-pipeline/cccp-delivery",
        "container-pipeline/cccp-test",
        "container-pipeline/mail-server",
        "dharmit/centos-go",
        "dharmit/centos-jre",
        "dharmit/centosi-jre",
        "dharmit/maven33",
        "eclipse/centos-go",
        "eclipse/centos-jre",
        "eclipse/centos-python27",
        "eclipse/centos-python35",
        "eclipse/che-dev",
        "eclipse/che-launcher",
        "eclipse/che-server",
        "gluster/storagesig-gluster-centos",
        "jboss/base",
        "jboss/base-jdk",
        "jboss/keycloak",
        "jboss/keycloak-adapter-wildfly",
        "jboss/keycloak-ha-postgres",
        "jboss/keycloak-postgres",
        "jboss/wildfly",
        "kbsingh/openshift-nginx",
        "kbsingh/openshift-vault",
        "mohammedzee100/postgresql-9-2",
        "mohammedzee1000/postgresql",
        "mohammedzee1000/postgresql-9-3",
        "mohammedzee1000/postgresql-9-4",
        "mohammedzee1000/postgresql-9-5",
        "mohammedzee1000/postgresql-9-6",
        "openshift/base-centos7",
        "openshift/node",
        "openshift/openvswitch",
        "openshift/origin",
        "openshift/origin-base",
        "openshift/origin-custom-docker-builder",
        "openshift/origin-deployer",
        "openshift/origin-docker-builder",
        "openshift/origin-docker-registry",
        "openshift/origin-egress-router",
        "openshift/origin-f5-router",
        "openshift/origin-haproxy-router",
        "openshift/origin-haproxy-router-base",
        "openshift/origin-keepalived-ipfailover",
        "openshift/origin-pod",
        "openshift/origin-recycler",
        "openshift/origin-release",
        "openshift/origin-sti-builder",
        "pipeline-images/cccp-build",
        "pipeline-images/cccp-delivery",
        "pipeline-images/cccp-test",
        "pipeline-images/dockerfile-lint",
        "pipeline-images/mail-server",
        "pipeline-images/pipeline-scanner",
        "pipeline-images/scanner-rpm-verify",
        "pipeline-scanner/cccp-build",
        "postgresql/postgresql",
        "projectatomic/atomic-registry-install",
        "sclo/devtoolset-4-perftools-centos7",
        "sclo/devtoolset-4-toolchain-centos7",
        "sclo/httpd-24-centos7",
        "sclo/mariadb-100-centos7",
        "sclo/mariadb-101-centos7"
    ]
}
```

**Comment by mohammedzee1000** [comment]
The container now needs to go into the container index, the PR for the same has been raised already.

https://github.com/CentOS/container-index/pull/80

**Comment by surajssd** [comment]
@mohammedzee1000 thanks for the pointer!

**Pull request merged**
