### PR TITLE
Feature/sonarqube

### LINKED ISSUE #8: Provide a CentOS version
There is this pattern of providing both a RHEL based and a CentOS based version of an OpenShift template. This helps OpenSource adoption and also advertises Red Hat supported images.

Thoughts? 

Note @goern has a CentOS version: https://github.com/goern/docker-rhel-sonarqube/tree/centos7

ping @goern @tchughesiv

### PR DESCRIPTION
**Pull request by goern**
This is a CentOS7 based SonarQube 6.1/6.2 with all the OpenShift stuff that one may need. It is derived directly from https://github.com/RHsyseng/docker-rhel-sonarqube/ 

This closes https://github.com/RHsyseng/docker-rhel-sonarqube/issues/8

### CODE REVIEW

**Comment by mohammedzee1000** [comment]
Could we have a cccp.yml file added to be able to build this on the  CentOS Container Pipeline.
https://github.com/CentOS/container-index/blob/master/cccp.yml should provide a template. Its the job-id that is compulsory and should be the name of the container.

**Comment by mohammedzee1000** [comment]
@kbsingh could you review this PR

**Comment by kbsingh** [comment]
lgtm

**Comment by mohammedzee1000** [comment]
@goern if you can add a cccp.yml file as i have stated above, we should be good with this

**Pull request closed without merging**
