### PR TITLE
Updated couchdb to build from source as we dont have rpms anymore.

### PR DESCRIPTION
**Pull request by mohammedzee1000**
This is towards the issue https://github.com/CentOS/CentOS-Dockerfiles/issues/89

### CODE REVIEW

**Comment by jperrin** [comment]
If it's possible, I'd like to see a few things in this so line up with what would be expected of an rpm. 

If the install script can do gpg validation of the tarball being pulled. 
Logging/output might also need to be handled a bit differently for proper debugging of the container. If you're able to accommodate those two things, I'm happy to pull this in.

**Comment by mohammedzee1000** [comment]
Well i have a decent idea about gpg verification as there is an asc file in the repository.
What changes would you recommend though towards the logging.

**Comment by jperrin** [comment]
For logging I'd say either throw it to stdout/stderr so that 'docker logs' works, or kill it entirely by logging to /dev/null.

**Comment by mohammedzee1000** [comment]
Hi,
I have added check for gpg key based on asc file present in same repository.

As far as logging is concerned, i checked and found that logs already get dumped on the stdout. Here is a sample.

```
$ docker run -d test_couch
<id of couchdb container>
$ docker logs <id of couch container>
Apache CouchDB 1.6.1 (LogLevel=info) is starting.
Apache CouchDB has started. Time to relax.
[info] [<0.32.0>] Apache CouchDB has started on http://0.0.0.0:5984/
```

The container itself is functional:

```
$ curl <ip_of_container_got_from_inspect>
{"couchdb":"Welcome","uuid":"125826e3133ff2d46fb9f52720a56254","version":"1.6.1","vendor":{"version":"1.6.1","name":"The Apache Software Foundation"}}
```

**Pull request merged**
